"""empty message

Revision ID: 069bc3153839
Revises: 4798e3e0aaa2
Create Date: 2021-08-10 15:11:40.732294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069bc3153839'
down_revision = '4798e3e0aaa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novel', sa.Column('volume_sub', sa.String(length=20), nullable=True))
    op.add_column('novel', sa.Column('volume_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novel', 'volume_content')
    op.drop_column('novel', 'volume_sub')
    # ### end Alembic commands ###
