"""empty message

Revision ID: 11eee1123558
Revises: 069bc3153839
Create Date: 2021-08-10 15:16:25.746753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11eee1123558'
down_revision = '069bc3153839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novel', 'volume_content')
    op.drop_column('novel', 'volume_sub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novel', sa.Column('volume_sub', sa.VARCHAR(length=20), nullable=True))
    op.add_column('novel', sa.Column('volume_content', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
