"""empty message

Revision ID: 4798e3e0aaa2
Revises: 741f3099415a
Create Date: 2021-08-10 15:05:58.517530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4798e3e0aaa2'
down_revision = '741f3099415a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novel', sa.Column('volume_sub', sa.String(length=20), nullable=False))
    op.add_column('novel', sa.Column('volume_content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novel', 'volume_content')
    op.drop_column('novel', 'volume_sub')
    # ### end Alembic commands ###
