"""empty message

Revision ID: 56689ac1f422
Revises: 07c17a82fab1
Create Date: 2021-08-27 16:45:13.255389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56689ac1f422'
down_revision = '07c17a82fab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['number_id'], ['number.id'], name=op.f('fk_comment_number_id_number'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_comment_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    with op.batch_alter_table('novel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('number', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    with op.batch_alter_table('number', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    with op.batch_alter_table('novel', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    op.drop_table('comment')
    # ### end Alembic commands ###
