"""empty message

Revision ID: 76634594accd
Revises: 44cd220c393a
Create Date: 2021-09-03 17:44:51.159237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76634594accd'
down_revision = '44cd220c393a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('novel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_novel_id_novel'), 'novel', ['novel_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_novel_id_novel'), type_='foreignkey')
        batch_op.drop_column('novel_id')

    # ### end Alembic commands ###
